name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        bazel: [ 4.2.1, 5.0.0-pre.20211011.2 ]
    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} bazel ${{ matrix.bazel }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel-${{ matrix.os }}-${{ matrix.bazel }}
      - name: Mount bazel repo cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel-repo
          key: bazel-repo-${{ matrix.os }}-${{ matrix.bazel }}
      - name: Set Bazelisk Version ${{ matrix.bazel }}
        run: echo ${{ matrix.bazel }} > .bazelversion
      - name: Build & Test
        env:
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc build //...
